### ISSUE TITLE
Errors in the Tutorial_ExTrack.ipynb

### ISSUE THREAD

**Issue by aherbert** [vanTeeffelenLab/ExTrack#2]
I have installed all deps into a fresh conda env and installed ExTrack from the git repo.

I found an error when stepping through the notebook `Tutorial_ExTrack.ipynb` during the step using `extrack.tracking.param_fitting`:

```
...

File /data/miniconda3b/envs/extrack/lib/python3.11/site-packages/extrack-1.5.6-py3.11.egg/extrack/tracking.py:604, in P_Cs_inter_bound_stats_th(Cs, LocErr, ds, Fs, TrMat, pBL, isBL, cell_dims, nb_substeps, frame_len, do_preds, min_len, threshold, max_nb_states)
    601     s2_arr = cp.repeat(s2_arr, nb_states**nb_substeps, axis = 1)
    602     LP = cp.repeat(LP, nb_states**nb_substeps, axis = 1)
--> 604     end_p_stay.shape
    605     LL = cp.log(pBL + (1-end_p_stay) - pBL * (1-end_p_stay)) + LT
    607 new_s2_arr = cp.array((s2_arr + LocErr2[:,:, min(LocErr_index, nb_locs-current_step)]))

NameError: name 'end_p_stay' is not defined
```

The `end_p_stay` range is created just before its use in function `P_Cs_inter_bound_stats`.

It is not created in the function `P_Cs_inter_bound_stats_th` (hence the above error). I copied the code to define `end_p_stay` into this function and fitting work, i.e.

```Python
        end_p_stay = p_stay[cur_states[:,None:,:-1]][:,:,0]
        end_p_stay.shape
        LL = cp.log(pBL + (1-end_p_stay) - pBL * (1-end_p_stay)) + LT
```

**Comment by FrancoisSimon** [comment]
Hi,
Thank you very much for noticing this error. I probably erased this line without paying enough attention. Sorry for the loss of time. I have corrected the error and I am also working on improving the tutorial and cleaning the tracking code a bit too.

**Comment by FrancoisSimon** [comment]
Hi,
Thank you very much for noticing this error. I probably erased this line without paying enough attention. Sorry for the loss of time. I have corrected the error and I am also working on improving the tutorial and cleaning the tracking code a bit too. Do not hesitate if you have any other comment or suggestion !
Best wishes
Francois
